defmodule DiversifWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :diversif

  # Cloudflare Tunnel signals scheme via `CF-Visitor`, not
  # `X-Forwarded-Proto`. The shim hooks via `@before_compile` so it lands
  # AFTER `Plug.Builder.__before_compile__` installs the endpoint's base
  # `call/2`. A naked `defoverridable call: 2` in the module body would
  # fail because `call/2` isn't defined yet at that point. See
  # `DiversifWeb.CloudflareVisitor` for the full why.
  @before_compile DiversifWeb.CloudflareVisitor

  # Belt-and-suspenders for the same problem at the next layer: Plug.RewriteOn
  # re-derives scheme / host / port from the `x-forwarded-*` headers for any
  # downstream plug that runs AFTER Plug.SSL (cookie `secure` flag, URL
  # generators, etc.). Plug.SSL itself uses its own `:rewrite_on` option
  # (set in `config/prod.exs`) which fires before this plug; that's the
  # piece that breaks the redirect loop. This one keeps `conn.scheme` :https
  # for everything that comes after.
  plug Plug.RewriteOn, [:x_forwarded_proto, :x_forwarded_host, :x_forwarded_port]

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_diversif_key",
    signing_salt: "UmVUkZ/F",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :diversif,
    gzip: not code_reloading?,
    only: DiversifWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :diversif
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DiversifWeb.Router
end
