import * as Sentry from '@sentry/sveltekit';
import { env } from '$env/dynamic/public';
import type { HandleClientError } from '@sveltejs/kit';
import { scrubEvent, filterIncomingBreadcrumb } from '$lib/sentry';

// No paraglide bootstrap is needed here since the 2.x migration: the
// runtime's `url` strategy re-reads window.location on every getLocale()
// call, so the locale is correct before hydration and across client-side
// navigations (the layout still syncs <html lang>).

Sentry.init({
  dsn: env.PUBLIC_SENTRY_DSN || '',
  environment: env.PUBLIC_SENTRY_ENVIRONMENT || 'production',
  // Inlined at build time by Vite's `define` (vite.config.ts), so the
  // server-side SHA and the client bundle share one constant. The define
  // emits either a string literal or the bare `undefined` token, so no
  // runtime fallback is needed here.
  release: __SENTRY_RELEASE__,
  tracesSampleRate: 0,
  // Explicitly opt out of default PII (IP address, cookies, user agent).
  // This is v8's default but we set it explicitly so a future SDK upgrade
  // that flips the default doesn't silently leak browser identifiers into
  // every event's user object.
  sendDefaultPii: false,
  // @ts-expect-error - Sentry's `Breadcrumb` type has no string-index signature,
  // so its `ErrorEvent.breadcrumbs` is not structurally assignable to our
  // isomorphic `ScrubbableEvent.breadcrumbs` (we keep the `[key: string]: unknown`
  // on our type so we can clone breadcrumb data with `{ ...b, data }`). Drop this
  // suppression if either type tightens : it'll fail loudly via @ts-expect-error.
  beforeSend: scrubEvent,
  beforeBreadcrumb: filterIncomingBreadcrumb
});

// Tags omit `method` (which the server hook records): SvelteKit's
// `NavigationEvent` has no `request` property in the browser, and there is no
// reliable equivalent (clicks, popstate, programmatic navigations all reach
// here without a method). They also omit `errorId` since that token is
// generated by the server's handleError; client errors have no equivalent.
//
// 4xx are skipped to match the server-side gate: client-side 404s (e.g. a
// data-load throwing notFound) are routing dead-ends, not bugs. Only 5xx
// reach Sentry.
export const handleError: HandleClientError = ({ error, event, status, message: _message }) => {
  if (status < 500) {
    return { message: 'Internal Error' };
  }
  Sentry.captureException(error, {
    tags: {
      status,
      route: event.route?.id ?? null
    }
  });
  return { message: 'Internal Error' };
};
